# Generated by Django 5.2.5 on 2025-09-15 21:27

import AppTienda.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[AppTienda.validators.CorporateEmailValidator()]),
        ),
    ]
