# Generated by Django 5.2.5 on 2025-09-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0007_alter_product_price_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
